#!/bin/bash

sudo apt-get install -y firefox-esr
sudo apt-get install -y firefox-esr-l10n-hu
sudo apt-get install -y webext-ublock-origin-firefox
sudo apt-get install -y curl
sudo apt-get install -y ktorrent
sudo apt-get install -y clementine
sudo apt-get install -y smplayer
sudo apt-get install -y kate
sudo apt-get install -y kamoso
sudo apt-get install -y kio-fuse
sudo apt-get install -y kio-gdrive
sudo apt-get install -y kio-audiocd
sudo apt-get install -y kaccounts-integration
sudo apt-get install -y qapt-deb-installer
sudo apt-get install -y qapt-utils
sudo apt-get install -y gimp
sudo apt-get install -y gimp-help-hu
sudo apt-get install -y gnome-disk-utility
sudo apt-get install -y vainfo
sudo apt-get install -y debian-goodies
sudo apt-get install -y moreutils
sudo apt-get install -y net-tools
sudo apt-get install -y lm-sensors
sudo apt-get install -y psensor
sudo apt-get install -y stress
sudo apt-get install -y inxi
sudo apt-get install -y dmidecode
sudo apt-get install -y htop
sudo apt-get install -y cups
sudo apt-get install -y system-config-printer
sudo apt-get install -y printer-driver-all
sudo apt-get install -y printer-driver-cups-pdf
sudo apt-get install -y printer-driver-hpijs
sudo apt-get install -y print-manager
sudo apt-get install -y sane
sudo apt-get install -y libsane
sudo apt-get install -y sane-utils
sudo apt-get install -y skanlite
sudo apt-get install -y avahi-daemon
sudo apt-get install -y avahi-utils
sudo apt-get install -y libnss-mdns
sudo apt-get install -y avahi-autoipd
sudo apt-get install -y bluetooth
sudo apt-get install -y bluez
sudo apt-get install -y bluez-alsa-utils
sudo apt-get install -y bluez-cups
sudo apt-get install -y bluez-firmware
sudo apt-get install -y bluez-tools
sudo apt-get install -y ufw
sudo apt-get install -y gufw
sudo apt-get install -y plasma-firewall
sudo apt-get install -y fonts-*
sudo apt-get install -y desktop-file-utils

echo 'A TELEPÍTÉS BEFEJEZŐDÖTT, KÉREM, HOGY INDÍTSA ÚJRA A SZÁMÍTÓGÉPÉT!'
